url_discovery:

  sitemap:
    timeout: 10
    retry: 3
    common_paths:
      - "/sitemap.xml"
      - "/sitemaps.xml"
      - "/sitemap_index.xml"
      - "/sitemap/sitemap.xml"
      - "/sitemap-index.xml"
    headers:
      User-Agent: "Mozilla/5.0"
      Accept: "application/xml,text/xml;q=0.9,*/*;q=0.8"
      Accept-Language: "en-US,en;q=0.9"
      Accept-Encoding: "gzip, deflate, br"
      Connection: "keep-alive"
      Upgrade-Insecure-Requests: "1"

  crawler:
    max_pages: 200
    concurrency: 30
    timeout: 10000
    load_state: "networkidle"
